name: affini
description: "Afini is an app designed for couples to simplify and enhance their relationship. It helps partners plan and schedule meet-ups, date nights, and special moments with minimal effort, strengthening their connection."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  go_router: ^14.6.1
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  dio: ^5.7.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand-SemiBold.ttf
